<script>
  import { link } from "svelte-routing";

  // core components
  const nimLogo = "/assets/img/nim-logo.svg"

</script>

<svelte:head>
  <title>Nim Wiki - Apply</title>
</svelte:head>


<section class="relative flex h-screen bg-secondary-dark bg-no-repeat">
  <a
    href="/"
    class="absolute top-0 left-0 max-w-150-px"
    style="margin-left: 50px; margin-top: 50px;"
  >
    <img
      src="{nimLogo}"
      alt="Nim Language Logo"
    />
  </a>
    
  <div class="container mx-auto grid justify-items-center max-h-860-px">
    <h2 class="font-semibold text-4xl text-primary mt-48">
      Domain directory
    </h2>

    <div class="flex items-baseline justify-between w-full max-w-6xl">
      <span class="text-2xl text-primary mr-4">
        <a
          href="https://nim-lang.nim.wiki"
          class="text-primary font-bold"
          target="_blank"
        >
          nim-lang.nim.wiki
        </a>
      </span>

      <span class="text-xl text-white ml-4">
        Nim is a statically typed compiled systems programming language.
      </span>
      
    </div>

    <div class="flex items-baseline justify-between w-full max-w-6xl">
      <span class="text-2xl text-primary mr-4">
        <a
          href="https://nim-wiki.nim.wiki"
          class="text-primary font-bold"
          target="_blank"
        >
          nim-wiki.nim.wiki
        </a>
      </span>

      <span class="text-xl text-white ml-4">
        An example to show what the end result of linking to a GitHub Page webpage
        would be.
      </span>
      
    </div>

    <div class="flex items-baseline justify-between w-full max-w-6xl">
      <span class="text-2xl text-primary mr-4">
        <a
          href="https://nimdicators.nim.wiki"
          class="text-primary font-bold"
          target="_blank"
        >
          nimdicators.nim.wiki
        </a>
      </span>

      <span class="text-xl text-white ml-4">
        An unfinished library that is another example. If this was a well documented Nim project
        then there would be nim docs generated by the compiler to show.
      </span>
      
    </div>

   

  </div>
</section>
